### ISSUE TITLE
This might not supposed to be public according to Coursera Honor Code

### ISSUE THREAD

**Issue by satouriko** [yhyap/machine-learning-coursera#2]
This might not supposed to be public according to [Coursera Honor Code](https://learner.coursera.help/hc/en-us/articles/209818863).

Just a kind reminder. Feel free to close the issue.:yum:

**Comment by GreatBahram** [comment]
You have to change line 47 to this: 
X_norm=(mu)./sigma
**X_mu** does not exist in this code!

**Comment by licaoyuan123** [comment]
> Given a new x value (living room area and number of bedrooms), we must first normalize x using the mean and standard deviation
that we had previously computed from the training set.

Which means when calculate the price, you need to use `price = [1 ( ([1650 3]-mu)./sigma)] * theta;` instead of line 107
